# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tictactoe.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftictactoe.proto\"\x11\n\x0f\x44\x61teTimeRequest\"%\n\x10\x44\x61teTimeResponse\x12\x11\n\tdate_time\x18\x01 \x01(\t2E\n\x0f\x44\x61teTimeService\x12\x32\n\x0bGetDateTime\x12\x10.DateTimeRequest\x1a\x11.DateTimeResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tictactoe_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATETIMEREQUEST._serialized_start=19
  _DATETIMEREQUEST._serialized_end=36
  _DATETIMERESPONSE._serialized_start=38
  _DATETIMERESPONSE._serialized_end=75
  _DATETIMESERVICE._serialized_start=77
  _DATETIMESERVICE._serialized_end=146
# @@protoc_insertion_point(module_scope)
